--[[
	Abyssara – Deep Tide Tycoon
	ApplyMeshes (Studio Command Bar script)

	GENERATED by tools/mesh-gen/make_apply_script.py – do not edit by hand,
	edit tools/mesh-gen/apply_template.lua and regenerate.

	What it does:
		Swaps the part-built models under Workspace.Assets for the smooth,
		textured meshes from assets/meshes/. Run it in Edit mode AFTER:
			1. all buildscripts in assets/models/** have been run, and
			2. every assets/meshes/<ModelName>/<ModelName>.glb has been
			   imported with the 3D Importer (File -> Import 3D) into a
			   Folder named "MeshImports" in Workspace, so that
			   Workspace.MeshImports.<ModelName> holds the MeshParts
			   (named Body, TailFin, Eye1, ...) with their SurfaceAppearance.

		Every model whose import is complete is swapped. Models without an
		import (or with missing meshes) keep their parts – nothing breaks.
		Part names, the PrimaryPart, attributes, tags, attachments,
		ProximityPrompts, lights and particles are carried over, so the
		game code and the animations (IdleSway, NpcAmbientController) work
		unchanged. Running it twice is safe: swapped models are skipped.
		MeshImports can be deleted afterwards; then save/publish the place.
]]

local Workspace = game:GetService("Workspace")
local CollectionService = game:GetService("CollectionService")

local LAYOUT = {
	GoldGuppy = { Meshes = {
		{ Name = "Body", Center = {-0.00148, 0.0008, -0.00175, 1, 0, 0, 0, 1, 0, 0, 0, 1}, Pivot = {0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1}, Size = {1.1571, 1.2528, 1.7422}, Material = "Foil", Transparency = 0, Replaces = { { Name = "Body", Pos = {0, 0, 0} } } },
		{ Name = "DorsalFin", Center = {-0.00067, 0.74906, -0.09777, -1, 0, 0, 0, 0.93969, 0.34202, 0, 0.34202, -0.93969}, Pivot = {0, 0.75, -0.1, -1, 0, 0, 0, 0.93969, 0.34202, 0, 0.34202, -0.93969}, Size = {0.1614, 0.5467, 0.6203}, Material = "Foil", Transparency = 0, Replaces = { { Name = "DorsalFin", Pos = {0, 0.75, -0.1} } } },
		{ Name = "Eye1", Center = {-0.4, 0.22, -0.75, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Pivot = {-0.4, 0.21, -0.85, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Size = {0.32, 0.3189, 0.2591}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "Eye1", Pos = {-0.4, 0.21, -0.85} }, { Name = "EyeWhite1", Pos = {-0.4, 0.22, -0.75} }, { Name = "EyeHighlight1", Pos = {-0.45, 0.27, -0.91} } } },
		{ Name = "Eye2", Center = {0.4, 0.22, -0.75, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Pivot = {0.4, 0.21, -0.85, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Size = {0.32, 0.3189, 0.2591}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "Eye2", Pos = {0.4, 0.21, -0.85} }, { Name = "EyeWhite2", Pos = {0.4, 0.22, -0.75} }, { Name = "EyeHighlight2", Pos = {0.35, 0.27, -0.91} } } },
		{ Name = "TailFin", Center = {-0.00036, -0.00135, 1.1695, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Pivot = {0, 0, 0.75, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Size = {0.8904, 0.5014, 0.9563}, Material = "Foil", Transparency = 0, Replaces = { { Name = "TailFin", Pos = {0, 0, 0.75} }, { Name = "TailLamella1", Pos = {-0.18779, 0, 1.1032} }, { Name = "TailLamella1Tip", Pos = {-0.3521, 0, 1.4122} }, { Name = "TailLamella2", Pos = {0, 0, 1.15} }, { Name = "TailLamella2Tip", Pos = {0, 0, 1.5} }, { Name = "TailLamella3", Pos = {0.18779, 0, 1.1032} }, { Name = "TailLamella3Tip", Pos = {0.3521, 0, 1.4122} } } },
		{ Name = "SideFin1", Center = {-0.42201, -0.11897, -0.15204, -0.90631, 0.42262, 0, 0.42262, 0.90631, 0, 0, 0, -1}, Pivot = {-0.42, -0.12, -0.15, -0.90631, 0.42262, 0, 0.42262, 0.90631, 0, 0, 0, -1}, Size = {0.4499, 0.1372, 0.3979}, Material = "Foil", Transparency = 0, Replaces = { { Name = "SideFin1", Pos = {-0.42, -0.12, -0.15} } } },
		{ Name = "SideFin2", Center = {0.42022, -0.11953, -0.15012, -0.90631, -0.42262, 0, -0.42262, 0.90631, 0, 0, 0, -1}, Pivot = {0.42, -0.12, -0.15, -0.90631, -0.42262, 0, -0.42262, 0.90631, 0, 0, 0, -1}, Size = {0.4451, 0.137, 0.3972}, Material = "Foil", Transparency = 0, Replaces = { { Name = "SideFin2", Pos = {0.42, -0.12, -0.15} } } },
	} },
	Shopkeeper = { Meshes = {
		{ Name = "Body", Center = {0.00098, -0.00505, 0.00499, 1, 0, -0, 0, 1, 0, -0, 0, 1}, Pivot = {0, 0, 0, 1, 0, -0, 0, 1, 0, -0, 0, 1}, Size = {3.6719, 2.6089, 3.3009}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "Body", Pos = {0, 0, 0} }, { Name = "ShellMark", Pos = {0.59999, 0.5, -1} }, { Name = "EyeStalkL", Pos = {-0.32001, -0.05, -1.95} }, { Name = "EyeStalkR", Pos = {0.31999, -0.05, -1.95} }, { Name = "BlushL", Pos = {-0.55001, -0.15, -2.1} }, { Name = "BlushR", Pos = {0.54999, -0.15, -2.1} }, { Name = "Satchel", Pos = {1.0118e-05, -0.35, 1.3} }, { Name = "SatchelFlap", Pos = {1.1147e-05, 0.15, 1.5} }, { Name = "SatchelBuckle", Pos = {1.0942e-05, -0.1, 1.46} }, { Name = "SatchelCoin1", Pos = {-0.31999, -0.8, 1.45} }, { Name = "SatchelCoin2", Pos = {4.0302e-06, -0.8, 1.45} }, { Name = "SatchelCoin3", Pos = {0.32001, -0.8, 1.45} } } },
		{ Name = "Head", Center = {-0.00283, -0.698, -1.6464, 1, 0, -0, 0, 1, 0, -0, 0, 1}, Pivot = {-1e-05, -0.7, -1.65, 1, 0, -0, 0, 1, 0, -0, 0, 1}, Size = {1.395, 1.155, 1.0971}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "Head", Pos = {-5.0592e-06, -0.7, -1.65} }, { Name = "Mouth", Pos = {-7.1172e-06, -0.2, -2.05} } } },
		{ Name = "Eye1", Center = {-0.32001, 0.22, -2.15, 1, 0, -0, 0, 1, 0, -0, 0, 1}, Pivot = {-0.32001, 0.22, -2.15, 1, 0, -0, 0, 1, 0, -0, 0, 1}, Size = {0.2994, 0.3, 0.2994}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "Eye1", Pos = {-0.32001, 0.22, -2.15} }, { Name = "EyePupilL", Pos = {-0.34001, 0.22, -2.3} }, { Name = "EyeGlintL", Pos = {-0.27001, 0.29, -2.36} } } },
		{ Name = "Eye2", Center = {0.31999, 0.22, -2.15, 1, 0, -0, 0, 1, 0, -0, 0, 1}, Pivot = {0.31999, 0.22, -2.15, 1, 0, -0, 0, 1, 0, -0, 0, 1}, Size = {0.2994, 0.3, 0.2994}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "Eye2", Pos = {0.31999, 0.22, -2.15} }, { Name = "EyePupilR", Pos = {0.33999, 0.22, -2.3} }, { Name = "EyeGlintR", Pos = {0.40999, 0.29, -2.36} } } },
		{ Name = "ArmL", Center = {-1.636, 0.09704, -0.37055, 0.91354, 0, 0.40674, 0, 1, 0, -0.40674, 0, 0.91354}, Pivot = {-1.9, 0.1, -0.39999, 0.91354, 0, 0.40674, 0, 1, 0, -0.40674, 0, 0.91354}, Size = {1.3065, 0.8431, 1.1168}, Material = "Neon", Transparency = 0, Replaces = { { Name = "ArmL", Pos = {-1.9, 0.1, -0.39999} }, { Name = "ArmStalkL", Pos = {-1.4, 0.1, -0.34999} } } },
		{ Name = "ArmR", Center = {1.6326, 0.09757, -0.36985, 0.91354, 0, -0.40674, 0, 1, 0, 0.40674, 0, 0.91354}, Pivot = {1.9, 0.1, -0.40001, 0.91354, 0, -0.40674, 0, 1, 0, 0.40674, 0, 0.91354}, Size = {1.304, 0.8422, 1.1213}, Material = "Neon", Transparency = 0, Replaces = { { Name = "ArmR", Pos = {1.9, 0.1, -0.40001} }, { Name = "ArmStalkR", Pos = {1.4, 0.1, -0.35001} } } },
		{ Name = "ClawTipL", Center = {-2.3482, 0.15136, -0.60004, 0.91354, 0, 0.40674, 0, 1, 0, -0.40674, 0, 0.91354}, Pivot = {-2.35, 0.15, -0.59999, 0.91354, 0, 0.40674, 0, 1, 0, -0.40674, 0, 0.91354}, Size = {0.4478, 0.318, 0.5515}, Material = "Neon", Transparency = 0, Replaces = { { Name = "ClawTipL", Pos = {-2.35, 0.15, -0.59999} } } },
		{ Name = "ClawTipR", Center = {2.351, 0.14948, -0.60053, 0.91354, 0, -0.40674, 0, 1, 0, 0.40674, 0, 0.91354}, Pivot = {2.35, 0.15, -0.60001, 0.91354, 0, -0.40674, 0, 1, 0, 0.40674, 0, 0.91354}, Size = {0.4477, 0.3163, 0.5445}, Material = "Neon", Transparency = 0, Replaces = { { Name = "ClawTipR", Pos = {2.35, 0.15, -0.60001} } } },
		{ Name = "Leg1", Center = {-1.1003, -0.9989, 0.80001, 0.88295, 0.46947, -0, -0.46947, 0.88295, 0, -1e-05, -0, 1}, Pivot = {-1.1, -1, 0.80001, 0.88295, 0.46947, -0, -0.46947, 0.88295, 0, -1e-05, -0, 1}, Size = {0.3006, 0.8498, 0.2977}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "Leg1", Pos = {-1.1, -1, 0.80001} } } },
		{ Name = "Leg2", Center = {-1.3003, -0.9989, -0.29999, 0.88295, 0.46947, -0, -0.46947, 0.88295, 0, -1e-05, -0, 1}, Pivot = {-1.3, -1, -0.29999, 0.88295, 0.46947, -0, -0.46947, 0.88295, 0, -1e-05, -0, 1}, Size = {0.3006, 0.8498, 0.2977}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "Leg2", Pos = {-1.3, -1, -0.29999} } } },
		{ Name = "Leg3", Center = {1.1009, -1.0024, 0.80007, 0.88295, -0.46947, -0, 0.46947, 0.88295, 0, -1e-05, 0, 1}, Pivot = {1.1, -1, 0.79999, 0.88295, -0.46947, -0, 0.46947, 0.88295, 0, -1e-05, 0, 1}, Size = {0.3026, 0.8498, 0.3045}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "Leg3", Pos = {1.1, -1, 0.79999} } } },
		{ Name = "Leg4", Center = {1.3008, -1.0012, -0.29955, 0.88295, -0.46947, -0, 0.46947, 0.88295, 0, -1e-05, 0, 1}, Pivot = {1.3, -1, -0.3, 0.88295, -0.46947, -0, 0.46947, 0.88295, 0, -1e-05, 0, 1}, Size = {0.2949, 0.8549, 0.2981}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "Leg4", Pos = {1.3, -1, -0.3} } } },
	} },
	TreasureTurtle = { Meshes = {
		{ Name = "Body", Center = {-0.00726, 0.76776, -0.43443, 1, 0, 0, 0, 1, 0, 0, 0, 1}, Pivot = {0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1}, Size = {3.5041, 3.1414, 5.8959}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "Body", Pos = {0, 0, 0} }, { Name = "ShellLower", Pos = {0, 0.55, 0.1} }, { Name = "Shell", Pos = {0, 1.15, 0.1} }, { Name = "ShellCap", Pos = {0, 1.85, 0.1} }, { Name = "ShellSeam1", Pos = {0, 1.55, 0.75} }, { Name = "ShellSeam2", Pos = {0, 1.55, -0.75} }, { Name = "ShellRim", Pos = {0, 0.35, 0.1} }, { Name = "KeyholeDetail", Pos = {0, 1.95, 0.1} }, { Name = "Neck", Pos = {0, 0.3, -1.75} }, { Name = "Head", Pos = {0, 0.45, -2.55} }, { Name = "Blush1", Pos = {-0.5, 0.25, -3} }, { Name = "Blush2", Pos = {0.5, 0.25, -3} }, { Name = "BeakDetail", Pos = {0, 0.1, -3.2} }, { Name = "HeadSmile", Pos = {0, -0.15, -3.28} }, { Name = "TailStub", Pos = {0, -0.05, 2.2} } } },
		{ Name = "Eye1", Center = {-0.5, 0.65, -3.05, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Pivot = {-0.5, 0.65, -3.23, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Size = {0.5, 0.5, 0.4}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "Eye1", Pos = {-0.5, 0.65, -3.23} }, { Name = "EyeWhite1", Pos = {-0.5, 0.65, -3.05} }, { Name = "EyeHighlight1", Pos = {-0.58, 0.73, -3.35} } } },
		{ Name = "Eye2", Center = {0.5, 0.65, -3.05, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Pivot = {0.5, 0.65, -3.23, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Size = {0.5, 0.5, 0.4}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "Eye2", Pos = {0.5, 0.65, -3.23} }, { Name = "EyeWhite2", Pos = {0.5, 0.65, -3.05} }, { Name = "EyeHighlight2", Pos = {0.42, 0.73, -3.35} } } },
		{ Name = "LegFrontLeft", Center = {-0.93009, -0.25002, -1.3035, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Pivot = {-0.93, -0.25, -1.3, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Size = {0.9535, 0.5477, 1.2959}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "LegFrontLeft", Pos = {-0.93, -0.25, -1.3} } } },
		{ Name = "LegFrontLeftTip", Center = {-1.5301, -0.30042, -1.2972, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Pivot = {-1.53, -0.3, -1.3, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Size = {0.7018, 0.3983, 0.8479}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "LegFrontLeftTip", Pos = {-1.53, -0.3, -1.3} } } },
		{ Name = "LegFrontRight", Center = {0.92991, -0.25002, -1.3035, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Pivot = {0.93, -0.25, -1.3, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Size = {0.9535, 0.5477, 1.2959}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "LegFrontRight", Pos = {0.93, -0.25, -1.3} } } },
		{ Name = "LegFrontRightTip", Center = {1.5299, -0.30042, -1.2972, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Pivot = {1.53, -0.3, -1.3, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Size = {0.7018, 0.3983, 0.8479}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "LegFrontRightTip", Pos = {1.53, -0.3, -1.3} } } },
		{ Name = "LegBackLeft", Center = {-0.89909, -0.25002, 1.5965, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Pivot = {-0.899, -0.25, 1.6, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Size = {0.9535, 0.5477, 1.2959}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "LegBackLeft", Pos = {-0.899, -0.25, 1.6} } } },
		{ Name = "LegBackLeftTip", Center = {-1.4991, -0.30042, 1.6028, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Pivot = {-1.499, -0.3, 1.6, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Size = {0.7018, 0.3983, 0.8479}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "LegBackLeftTip", Pos = {-1.499, -0.3, 1.6} } } },
		{ Name = "LegBackRight", Center = {0.89891, -0.25002, 1.5965, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Pivot = {0.899, -0.25, 1.6, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Size = {0.9535, 0.5477, 1.2959}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "LegBackRight", Pos = {0.899, -0.25, 1.6} } } },
		{ Name = "LegBackRightTip", Center = {1.4989, -0.30042, 1.6028, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Pivot = {1.499, -0.3, 1.6, -1, 0, 0, 0, 1, 0, 0, 0, -1}, Size = {0.7018, 0.3983, 0.8479}, Material = "SmoothPlastic", Transparency = 0, Replaces = { { Name = "LegBackRightTip", Pos = {1.499, -0.3, 1.6} } } },
	} },
}

local POSITION_TOLERANCE = 0.6

local function cframeFrom(values)
	return CFrame.new(table.unpack(values))
end

local function findImport(modelName)
	local imports = Workspace:FindFirstChild("MeshImports")
	return imports and imports:FindFirstChild(modelName)
end

local function findMeshPart(container, name)
	for _, d in ipairs(container:GetDescendants()) do
		if d:IsA("MeshPart") and d.Name == name then
			return d
		end
	end
	return nil
end

-- Buildscripts reuse names ("Scale", "Spot"), so every replaced part is
-- matched by name AND by its position relative to the PrimaryPart.
local function findReplacedPart(model, base, entry, taken)
	local expected = base * Vector3.new(table.unpack(entry.Pos))
	local best, bestDist = nil, POSITION_TOLERANCE
	for _, d in ipairs(model:GetDescendants()) do
		if d:IsA("BasePart") and d.Name == entry.Name and not taken[d] then
			local dist = (d.Position - expected).Magnitude
			if dist < bestDist then
				best, bestDist = d, dist
			end
		end
	end
	return best
end

local SKIPPED_CHILD_CLASSES = {
	SpecialMesh = true,
	BlockMesh = true,
	CylinderMesh = true,
	Texture = true, -- keyed tiling textures: the baked SurfaceAppearance replaces them
	Decal = true,
	SurfaceAppearance = true,
}

local function carryOver(oldPart, newPart)
	for name, value in pairs(oldPart:GetAttributes()) do
		if newPart:GetAttribute(name) == nil then
			newPart:SetAttribute(name, value)
		end
	end
	for _, tag in ipairs(CollectionService:GetTags(oldPart)) do
		CollectionService:AddTag(newPart, tag)
	end
	for _, child in ipairs(oldPart:GetChildren()) do
		if not SKIPPED_CHILD_CLASSES[child.ClassName] then
			if child:IsA("Attachment") then
				local world = child.WorldCFrame
				child.Parent = newPart
				child.WorldCFrame = world
			else
				child.Parent = newPart
			end
		end
	end
end

local function redirectJoints(model, mapping)
	for _, d in ipairs(model:GetDescendants()) do
		if d:IsA("WeldConstraint") or d:IsA("JointInstance") or d:IsA("NoCollisionConstraint") then
			local p0, p1 = (d :: any).Part0, (d :: any).Part1
			if p0 and mapping[p0] then
				(d :: any).Part0 = mapping[p0]
			end
			if p1 and mapping[p1] then
				(d :: any).Part1 = mapping[p1]
			end
		end
	end
end

local function swapModel(model, layout)
	local import = findImport(model.Name)
	if not import then
		return "no import"
	end
	local primary = model.PrimaryPart
	if not primary then
		return "no PrimaryPart"
	end
	for _, mesh in ipairs(layout.Meshes) do
		if not findMeshPart(import, mesh.Name) then
			return "import is missing mesh '" .. mesh.Name .. "'"
		end
	end

	local base = primary.CFrame
	local taken = {}
	local plan = {}
	for _, mesh in ipairs(layout.Meshes) do
		local parts = {}
		for _, entry in ipairs(mesh.Replaces) do
			local part = findReplacedPart(model, base, entry, taken)
			if part then
				taken[part] = true
				table.insert(parts, part)
			end
		end
		table.insert(plan, { Mesh = mesh, Parts = parts })
	end

	local mapping = {}
	local newPrimary = nil
	for _, step in ipairs(plan) do
		local mesh = step.Mesh
		local anchor = step.Parts[1]
		for _, part in ipairs(step.Parts) do
			if part.Name == mesh.Name then
				anchor = part
				break
			end
		end

		local newPart = findMeshPart(import, mesh.Name):Clone()
		for _, child in ipairs(newPart:GetChildren()) do
			if not child:IsA("SurfaceAppearance") then
				child:Destroy()
			end
		end
		local center = base * cframeFrom(mesh.Center)
		newPart.Name = mesh.Name
		newPart.Anchored = true
		newPart.Size = Vector3.new(table.unpack(mesh.Size))
		newPart.CFrame = center
		newPart.PivotOffset = center:Inverse() * (base * cframeFrom(mesh.Pivot))
		newPart.Material = Enum.Material[mesh.Material] or Enum.Material.SmoothPlastic
		newPart.Transparency = mesh.Transparency or 0
		if anchor then
			newPart.CanCollide = anchor.CanCollide
			newPart.CanQuery = anchor.CanQuery
			newPart.CanTouch = anchor.CanTouch
			newPart.CastShadow = anchor.CastShadow
		else
			newPart.CanCollide = false
		end
		newPart.Parent = anchor and anchor.Parent or model

		for _, part in ipairs(step.Parts) do
			carryOver(part, newPart)
			mapping[part] = newPart
			if part == primary then
				newPrimary = newPart
			end
		end
	end

	redirectJoints(model, mapping)
	for sub in pairs(mapping) do
		if sub.Parent and sub.Parent:IsA("Model") and (sub.Parent :: Model).PrimaryPart == sub then
			(sub.Parent :: Model).PrimaryPart = mapping[sub]
		end
	end
	if newPrimary then
		model.PrimaryPart = newPrimary
	end
	for old in pairs(mapping) do
		old:Destroy()
	end
	model:SetAttribute("MeshSwapped", true)
	return nil
end

local assets = Workspace:FindFirstChild("Assets")
if not assets then
	warn("[ApplyMeshes] Workspace.Assets is missing – run the buildscripts first.")
	return
end

local swapped, skipped = 0, 0
for _, model in ipairs(assets:GetDescendants()) do
	local layout = model:IsA("Model") and LAYOUT[model.Name]
	if layout and not model:GetAttribute("MeshSwapped") then
		local failure = swapModel(model, layout)
		if failure then
			skipped += 1
			print(("[ApplyMeshes] %s kept its parts (%s)"):format(model:GetFullName(), failure))
		else
			swapped += 1
		end
	end
end
print(("[ApplyMeshes] swapped %d model(s), %d kept their parts. Save or publish the place now."):format(swapped, skipped))
