--!strict
--[[
	Abyssara – Deep Tide Tycoon
	Module: TextureConfig
	Responsibility:
		Single source of truth for the Roblox asset IDs of the texture pack in
		assets/textures/<Key>.png (generated by tools/texture-gen/generate.py,
		documented in assets/textures/README.md).

		Buildscripts create Texture instances with Texture = "" and an
		attribute TextureKey = "<Key>". TextureApplier.client.lua looks the
		key up here and sets .Texture = "rbxassetid://" .. Id.

		Every Id below is intentionally empty: Roblox can only show images
		that were uploaded to Roblox. Empty Id = "not uploaded yet" - the
		applier then hides that texture (Transparency = 1) instead of showing
		a broken image. To fill in: Studio -> View -> Asset Manager -> Bulk
		Import the PNGs from assets/textures/, right-click each image ->
		Copy Asset ID, paste the number here (either "1234567890" or
		"rbxassetid://1234567890" works). See docs/release-checklist.md.

		StudsPerTile = recommended StudsPerTileU/V for a typical 4-10 stud
		model (buildscripts set their own values; the applier never changes
		them). Tintable = true means a white/dark overlay with alpha that takes
		the part color (and the Texture's Color3); false means the image has
		baked colors, so keep Color3 white.

	Rojo mount point:
		src/shared/TextureConfig.lua -> ReplicatedStorage.TextureConfig
]]

export type TextureEntry = {
	Id: string,
	StudsPerTile: number,
	Tintable: boolean,
}

local TextureConfig: { [string]: TextureEntry } = {
	-- Creatures: skins and shells
	FishScales = { Id = "", StudsPerTile = 2, Tintable = true },
	FishScalesFine = { Id = "", StudsPerTile = 1, Tintable = true },
	SharkSkin = { Id = "", StudsPerTile = 3, Tintable = true },
	JellyMembrane = { Id = "", StudsPerTile = 2, Tintable = true },
	CrabShell = { Id = "", StudsPerTile = 1.5, Tintable = true },
	IsopodPlates = { Id = "", StudsPerTile = 2, Tintable = true },
	TurtleShellHex = { Id = "", StudsPerTile = 3, Tintable = true },
	MothWing = { Id = "", StudsPerTile = 3, Tintable = true },
	EelStripes = { Id = "", StudsPerTile = 3, Tintable = true },
	SlugSpots = { Id = "", StudsPerTile = 2, Tintable = true },
	ToxicBlotches = { Id = "", StudsPerTile = 3, Tintable = true },
	GhostWisp = { Id = "", StudsPerTile = 4, Tintable = true },
	KelpFibers = { Id = "", StudsPerTile = 2, Tintable = true },

	-- Minerals, treasure, elements
	CoralPorous = { Id = "", StudsPerTile = 1.5, Tintable = true },
	CrystalFacets = { Id = "", StudsPerTile = 2, Tintable = true },
	GoldFoil = { Id = "", StudsPerTile = 2, Tintable = false }, -- baked gold
	CoinPile = { Id = "", StudsPerTile = 3, Tintable = false }, -- baked gold coins
	IceFrost = { Id = "", StudsPerTile = 3, Tintable = true },
	LavaCracks = { Id = "", StudsPerTile = 4, Tintable = false }, -- baked orange glow
	BioVeins = { Id = "", StudsPerTile = 3, Tintable = false }, -- baked cyan glow

	-- Buildings, props, terrain
	MetalPanels = { Id = "", StudsPerTile = 2, Tintable = true },
	RivetedPlates = { Id = "", StudsPerTile = 2.5, Tintable = true },
	WoodPlanks = { Id = "", StudsPerTile = 3, Tintable = true },
	StoneTiles = { Id = "", StudsPerTile = 3, Tintable = true },
	BasaltRock = { Id = "", StudsPerTile = 6, Tintable = true },
	SandRipples = { Id = "", StudsPerTile = 8, Tintable = true },

	-- Gacha eggs
	EggSpeckle = { Id = "", StudsPerTile = 1.5, Tintable = true },
	EggRunes = { Id = "", StudsPerTile = 2, Tintable = true },
}

return TextureConfig
